import { StyleSheet } from 'react-native'

export const appStyles = StyleSheet.create({

  container: {
    marginTop: 40,
    padding: 12,
  },
  verticallySpaced: {
    paddingTop: 4,
    paddingBottom: 4,
    alignSelf: 'stretch',
  },
  mt20: {
    marginTop: 20,
  },
  // --- Typography ---
  titleLogo: {
    fontFamily: 'Caveat-Regular',
    fontSize: 64,
    color: '#37423D',
  },
  titleHeadline1: {
    fontFamily: 'Caveat-Regular',
    fontSize: 40,
    lineHeight: 52,
    paddingHorizontal: 8,
    paddingVertical: 4,
    color: '#37423D',
  },
  titleHeadline2: {
    fontFamily: 'Caveat-Regular',
    fontSize: 34,
    lineHeight: 44,
    paddingHorizontal: 8,
    paddingVertical: 3,
    color: '#37423D',
  },
  titleHeadline3: {
    fontFamily: 'Caveat-Regular',
    fontSize: 28,
    lineHeight: 36,
    paddingHorizontal: 8,
    paddingVertical: 2,
    color: '#37423D',
  },
  titleHeadline4: {
    fontFamily: 'Caveat-Regular',
    fontSize: 18,
    lineHeight: 26,
    paddingHorizontal: 6,
    paddingVertical: 2,
    color: '#37423D',
  },
  titleParagraph: {
    fontFamily: 'Caveat-Regular',
    fontSize: 14,
    color: '#37423D',
  },
  subtitleHeadline1: {
    fontFamily: 'Raleway-Regular',
    fontSize: 40,
    color: '#37423D',
  },
  subtitleHeadline2: {
    fontFamily: 'Raleway-Regular',
    fontSize: 34,
    color: '#37423D',
  },
  subtitleHeadline3: {
    fontFamily: 'Raleway-Regular',
    fontSize: 28,
    color: '#37423D',
  },
  subtitleHeadline4: {
    fontFamily: 'Raleway-Regular',
    fontSize: 18,
    color: '#37423D',
  },
  subtitleParagraph: {
    fontFamily: 'Raleway-Regular',
    fontSize: 14,
    color: '#37423D',
  },
  bodyHeadline1: {
    fontFamily: 'Harmattan-Regular',
    fontSize: 40,
    color: '#37423D',
  },
  bodyHeadline2: {
    fontFamily: 'Harmattan-Regular',
    fontSize: 34,
    color: '#37423D',
  },
  bodyHeadline3: {
    fontFamily: 'Harmattan-Regular',
    fontSize: 28,
    color: '#37423D',
  },
  bodyHeadline4: {
    fontFamily: 'Harmattan-Regular',
    fontSize: 18,
    color: '#37423D',
    lineHeight: 26,
  },
  bodyParagraph: {
    fontFamily: 'Harmattan-Regular',
    fontSize: 14,
    color: '#37423D',
  },
  label: {
    fontFamily: 'Raleway-Medium',
    fontSize: 16,
    color: '#86939e',
    marginBottom: 6,
  },
  input: {
    borderWidth: 1,
    borderColor: '#86939e',
    borderRadius: 4,
    padding: 12,
    fontSize: 16,
  },
  inputDisabled: {
    backgroundColor: '#f2f2f2',
    borderColor: '#d1d1d1',
    color: '#9e9e9e',
  },
  button: {
    backgroundColor: '#899878',
    borderRadius: 30,
    alignItems: 'center',
  },
  buttonDisabled: {
    opacity: 0.5,
  },
  buttonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  avatarContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
  },
  avatar: {
    borderRadius: 5,
    overflow: 'hidden',
    maxWidth: '100%',
    marginBottom: 20,
  },
  image: {
    objectFit: 'cover',
    paddingTop: 0,
  },
  noImage: {
    backgroundColor: '#333',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'rgb(200, 200, 200)',
    borderRadius: 5,
  },
  backgroundColor: {
    flex: 1,
    backgroundColor: '#FCF9ED',
  },
  welcomeBlock: {
    flex: 1,
    backgroundColor: '#DDE7C7',

  },
  backgroundContainer: {
    flex: 1,
    backgroundColor: '#FCF9ED',
    // justifyContent: 'center',
    // alignItems:'center',
  },
  icon: {
    width: 24,
    height: 24,
  },
  // ----- Welcome Page Styles -----
  imageContainer: {
    backgroundColor: '#FCF9ED',
    paddingVertical: 56,
    zIndex: 1,
  },
  heroBlock: {
    flex: 1,
    backgroundColor: '#DDE7C7',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 24,
    paddingTop: 24,
    marginTop: -40,
    zIndex: 2,
  },
  introBlock: {
    alignItems: 'center',
    paddingTop: 6,
  },
  // ----------------------------
  // --- Profile Page Styles ---
  profileContainer: {
    // backgroundColor: '#06d6a0',
    justifyContent: 'center',
    alignItems: 'center',
  },
  settingContainer: {
    // backgroundColor: '#ffd166',
    paddingHorizontal: 14,
    paddingVertical: 22,
  },
  accountContainer: {
    // backgroundColor: '#4361ee',
    gap: 10,
    paddingBottom: 20,
  },
  settingsCard: {
    backgroundColor: '#ffffff',
    borderRadius: 20,
  },
  settingRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 12,
  },
  settingRowLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  divider: {
    height: 1,
    backgroundColor: '#918E8E',
  },
  myPlantContainer: {
    // backgroundColor: '#4cc9f0',
    gap: 10,
    paddingBottom: 20,

  },
  socialContainer: {
    // backgroundColor: '#f72585',
    gap: 10,
    paddingBottom: 20,
  },
  profileCircle: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: '#899878',
    marginTop: 71,
  },
  profileCircleImageClip: {
    width: 100,
    height: 100,
    borderRadius: 50,
    overflow: 'hidden',
    backgroundColor: '#DDE7C7',
    marginTop: 71,
  },
  profileCircleImage: {
    width: '100%',
    height: '100%',
  },
  profileCircle2: {
    width: 150,
    height: 150,
    borderRadius: 75,
    backgroundColor: '#899878',
    // marginTop: 71,
  },
  profileCircleImage2Clip: {
    width: 150,
    height: 150,
    borderRadius: 75,
    overflow: 'hidden',
    backgroundColor: '#DDE7C7',
  },
  profileCircleImage2: {
    width: '100%',
    height: '100%',
  },
  profileStatusContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 25,
    alignItems: 'center',
    marginTop: 8,
    marginBottom: 12,
  },
  streakContainer: {
    outlineStyle: 'solid',
    outlineColor: '#37423D',
    outlineWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
    height: 35,
    borderRadius: 40,
    paddingHorizontal: 12,
  },
  statsContainer: {
    backgroundColor: '#B9CCA4',
    justifyContent: 'center',
    alignItems: 'center',
    height: 35,
    borderRadius: 40,
    paddingHorizontal: 12,
  },
  friendsContainer: {
    outlineStyle: 'solid',
    outlineColor: '#37423D',
    outlineWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
    height: 35,
    borderRadius: 40,
    paddingHorizontal: 12,
  },
  scrollContent: {
    paddingBottom: 100,
  },
  // ------------------------------------
  screenHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 70,
  },
  screenContent: {
    paddingHorizontal: 16,
    alignItems: 'center',
  },
  userInputEmail: {
    paddingHorizontal: 16,
    paddingVertical: 20,
  },
  inputGroup: {
    gap: 6,
    marginBottom: 15,
  },
  gardenerPicker: {
    flexDirection: 'column',
    paddingHorizontal: 16,
    paddingVertical: 12,
    gap: 12,
  },
  gardenerOptionsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  gardenerOption: {
    width: 106,
    height: 106,
    borderRadius: 53,
    borderWidth: 3,
    borderColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'center',
  },
  gardenerOptionSelected: {
    borderColor: '#899878',
  },
  gardenerOptionImageWrapper: {
    width: 100,
    height: 100,
    borderRadius: 50,
    overflow: 'hidden',
    backgroundColor: '#F1EFE3',
  },
  gardenerOptionImage: {
    width: '100%',
    height: '100%',
  },
  gardenerOptionCheck: {
    position: 'absolute',
    bottom: -2,
    right: -2,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#899878',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#FCF9ED',
  },
  gardenerOptionLabel: {
    textAlign: 'center',
    marginTop: 6,
  },
  gardenerOptionColumn: {
    alignItems: 'center',
    width: 100,
  },
  saveButton: {
    backgroundColor: '#DDE7C7',
    borderRadius: 20,
    width: 250,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 20,
    alignSelf: 'center',
  },
  speciesOptionsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 20,
  },
  speciesOption: {
    width: 150,
    height: 150,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    paddingBottom: 10,
    borderWidth: 1,
    borderColor: '#E8E6D7',
  },
  speciesOptionAvailable: {
    backgroundColor: '#DDE7C7',
    borderColor: '#899878',
  },
  speciesOptionComingSoon: {
    backgroundColor: '#F1EFE3',
    borderStyle: 'dashed',
    borderColor: '#B9CCA4',
    gap: 6,
  },
  speciesOptionPressed: {
    opacity: 0.7,
  },
  speciesOptionImage: {
    width: 128,
    height: 128,
  },
  speciesOptionLabel: {
    marginTop: 6,
    color: '#37423D',
  },
  speciesOptionComingSoonLabel: {
    color: '#918E8E',
    textAlign: 'center',
    paddingHorizontal: 12,
  },
  potOption: {
    backgroundColor: '#F1EFE3',
  },
  potOptionSelected: {
    backgroundColor: '#DDE7C7',
    borderColor: '#899878',
  },
  potPreviewContainer: {
    marginTop: 32,
    alignItems: 'center',
  },
  potPreviewLabel: {
    color: '#918E8E',
    letterSpacing: 0.5,
  },
  potPreviewImage: {
    width: 190,
    height: 190,
    marginTop: 8,
  },
  saveButtonCompact: {
    width: 200,
    height: 36,
    marginTop: 12,
  },
  // ------- Log Out Component -------
  modalOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  modalSheet: {
    backgroundColor: '#FCF9ED',
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    paddingHorizontal: 24,
    paddingTop: 20,
    paddingBottom: 40,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 35,
  },
  modalCloseButton: {
    alignSelf: 'flex-start',
    marginBottom: 12,
  },
  modalTitle: {
    fontFamily: 'Raleway-Bold',
    fontSize: 20,
    color: '#e63946',
    textAlign: 'center',
  },
  modalQuestion: {
    fontFamily: 'Raleway-Bold',
    fontSize: 18,
    color: '#37423D',
    textAlign: 'center',
    marginBottom: 6,
  },
  modalSubtitle: {
    fontFamily: 'Raleway-Regular',
    fontSize: 14,
    color: '#918E8E',
    textAlign: 'center',
    marginBottom: 28,
  },
  modalButtonRow: {
    flexDirection: 'row',
    gap: 12,
  },
  modalCancelButton: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#37423D',
    borderRadius: 30,
    paddingVertical: 14,
    alignItems: 'center',
  },
  modalCancelText: {
    fontFamily: 'Raleway-SemiBold',
    fontSize: 16,
    color: '#37423D',
  },
  modalConfirmButton: {
    flex: 1,
    backgroundColor: '#B9CCA4',
    borderRadius: 30,
    paddingVertical: 14,
    alignItems: 'center',
  },
  modalConfirmText: {
    fontFamily: 'Raleway-SemiBold',
    fontSize: 16,
    color: '#37423D',
  },
  // ----------------------------------
  searchInputWrapper: {
    paddingHorizontal: 16,
    paddingVertical: 20,
    position: 'relative',
    justifyContent: 'center',
  },
  searchIcon: {
    position: 'absolute',
    left: 30,
    zIndex: 1,
  },
  searchInput: {
    borderRadius: 20,
    backgroundColor: '#ffffff',
    paddingLeft: 40,
  },
  friendsListContainer: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  noFriendsImage: {
    width: 300,
    height: 300,
    resizeMode: 'contain',
    alignSelf: 'center',
  },
  // ----------------------------------
  // -------- CARE PAGE STYLES --------
  careHero: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#D5B9B2',
    paddingTop: 60,
    paddingHorizontal: 20,
    borderBottomLeftRadius: 32,
    borderBottomRightRadius: 32,
  },
  careHeroText: {
    // flex: 1,
    // marginRight: 16,
    maxWidth: '70%',
  },
  careHeroImageWrapper: {
    width: '100%',
    maxWidth: 110,
    justifyContent: 'center',
    alignItems: 'center',
    // backgroundColor: '#6d61f5',
  },
  careGreeting: {
    fontFamily: 'Raleway-Regular',
    fontSize: 34,
    color: '#37423D',
    flexShrink: 1,
    // backgroundColor: '#f26eda',
  },
  careGreetingName: {
    fontFamily: 'Raleway-Bold',
  },
  careIllustration: {
    width: '100%',
    aspectRatio: 1,
    height: 300,
  },
  sectionLabel: {
    fontFamily: 'Raleway-Regular',
    fontSize: 18,
    color: '#918E8E',
    // marginTop: 20,
    // marginBottom: 10,
  },
  moodContainer: {
    paddingHorizontal: 20,
    paddingVertical: 13,
    gap: 10,
    // backgroundColor: '#a9cf58',
  },
  moodGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    rowGap: 12,
  },
  moodOption: {
    width: '47%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    backgroundColor: '#FFFFFF',
    borderRadius: 30,
    borderWidth: 1.5,
    borderColor: '#37423D',
  },
  moodOptionSelected: {
    opacity: 1,
    backgroundColor: '#DDE7C7',
  },
  moodLabel: {
    fontFamily: 'Harmattan-Regular',
    fontSize: 18,
    color: '#37423D',
    alignSelf: 'center',
  },
  moodImage: {
    width: 50,
    height: 50,
  },
  userInputContainer: {
    // backgroundColor: '#ffd07e',
    paddingHorizontal: 20,
    paddingVertical: 13,
    gap: 10,
  },
  noteInput: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E5E1DA',
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingTop: 14,
    paddingBottom: 14,
    minHeight: 90,
    maxHeight: 110,
    fontFamily: 'Raleway-Regular',
    fontSize: 14,
    lineHeight: 22,
    color: '#37423D',
    textAlignVertical: 'top',
  },
  characterCount: {
    fontFamily: 'Raleway-Regular',
    fontSize: 12,
    color: '#918E8E',
    alignSelf: 'flex-end',
    marginTop: -4,
  },
  sleepContainer: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    gap: 10,
    // backgroundColor: '#341b39',
  },
  sleepRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 24,
  },
  sleepButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: '#37423D',
    justifyContent: 'center',
    alignItems: 'center',
  },
  sleepHoursText: {
    fontFamily: 'Raleway-Bold',
    fontSize: 28,
    color: '#37423D',
  },
  sleepHoursWrapper: {
    width: 150,
    alignItems: 'center',
    justifyContent: 'center',
    // backgroundColor: '#F335D6'
  },
  nextContainer: {
    // flex: 1,
    justifyContent: 'flex-end',
    alignItems: 'center',
    paddingBottom: 120,
    // backgroundColor: '#F335D6'
  },

  nextButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    width: 210,
    height: 50,
    backgroundColor: '#DDE7C7',
    borderRadius: 30,
    borderWidth: 1.5,
    borderColor: '#37423D',
  },

  nextButtonDisabled: {
    backgroundColor: '#FFFFFF',
    opacity: 0.3,
  },

  nextButtonText: {
    fontFamily: 'Raleway-SemiBold',
    fontSize: 16,
    color: '#37423D',
  },
  careDevDayButton: {
    marginTop: 12,
    paddingVertical: 6,
    paddingHorizontal: 12,
  },
  careDevDayButtonText: {
    fontFamily: 'Raleway-Regular',
    fontSize: 11,
    color: '#6B716D',
    textDecorationLine: 'underline',
  },
  agentBackgroundContainer: {
    flex: 1,
    backgroundColor: '#D5B9B2'
  },
  agentHero: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#D5B9B2',
    paddingTop: 60,
    paddingHorizontal: 20,
  },
  agentLoadingScreen: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#D5B9B2',
    paddingHorizontal: 36,
    paddingBottom: 80,
  },
  agentLoadingImageWrapper: {
    width: 190,
    height: 190,
    borderRadius: 95,
    backgroundColor: '#E8D7D2',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 22,
  },
  agentLoadingImageClip: {
    width: 170,
    height: 170,
    borderRadius: 85,
    overflow: 'hidden',
  },
  agentLoadingImage: {
    width: '100%',
    height: '100%',
  },
  agentLoadingTitle: {
    fontFamily: 'Caveat-Regular',
    fontSize: 30,
    lineHeight: 38,
    color: '#37423D',
    textAlign: 'center',
  },
  agentLoadingText: {
    fontFamily: 'Raleway-Regular',
    fontSize: 14,
    lineHeight: 21,
    color: '#37423D',
    textAlign: 'center',
    marginTop: 12,
  },
  agentSpinner: {
    marginTop: 24,
  },
  agentErrorScreen: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FCF9ED',
    paddingHorizontal: 36,
    paddingBottom: 80,
  },
  agentErrorImage: {
    width: 150,
    height: 150,
    marginBottom: 18,
  },
  agentErrorTitle: {
    fontFamily: 'Caveat-Regular',
    fontSize: 30,
    lineHeight: 36,
    color: '#37423D',
    textAlign: 'center',
  },
  agentErrorText: {
    fontFamily: 'Raleway-Regular',
    fontSize: 14,
    lineHeight: 21,
    color: '#6B716D',
    textAlign: 'center',
    marginTop: 10,
  },
  agentRetryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#DDE7C7',
    borderColor: '#37423D',
    borderWidth: 1,
    borderRadius: 24,
    paddingHorizontal: 20,
    paddingVertical: 12,
    marginTop: 24,
  },
  agentRetryText: {
    fontFamily: 'Raleway-SemiBold',
    fontSize: 15,
    color: '#37423D',
  },
  agentPlanScreen: {
    flex: 1,
    backgroundColor: '#FCF9ED',
  },
  agentPlanContent: {
    paddingTop: 58,
    paddingHorizontal: 20,
    paddingBottom: 120,
  },
  agentPlanGreeting: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    padding: 14,
    shadowColor: '#37423D',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.16,
    shadowRadius: 4,
    elevation: 4,
  },
  agentPlanAvatarClip: {
    width: 56,
    height: 56,
    borderRadius: 28,
    overflow: 'hidden',
    backgroundColor: '#DDE7C7',
  },
  agentPlanAvatar: {
    width: '100%',
    height: '100%',
  },
  agentPlanGreetingText: {
    flex: 1,
    marginLeft: 12,
  },
  agentPlanGreetingTitle: {
    fontFamily: 'Harmattan-SemiBold',
    fontSize: 17,
    color: '#37423D',
  },
  agentPlanGreetingBody: {
    fontFamily: 'Raleway-Regular',
    fontSize: 12,
    lineHeight: 17,
    color: '#6B716D',
    marginTop: 2,
  },
  agentPlanHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    marginTop: 36,
  },
  agentPlanTitle: {
    fontFamily: 'Caveat-Regular',
    fontSize: 31,
    color: '#37423D',
  },
  agentPlanSubtitle: {
    fontFamily: 'Raleway-Regular',
    fontSize: 12,
    color: '#37423D',
    marginTop: -4,
  },
  agentProgressSection: {
    marginTop: 20,
  },
  agentProgressLabels: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 7,
  },
  agentProgressLabel: {
    fontFamily: 'Raleway-Regular',
    fontSize: 11,
    color: '#6B716D',
  },
  agentProgressTrack: {
    height: 6,
    borderRadius: 3,
    backgroundColor: '#E8E6D7',
    overflow: 'hidden',
  },
  agentProgressFill: {
    width: '0%',
    height: '100%',
    backgroundColor: '#899878',
  },
  agentTaskList: {
    gap: 15,
    marginTop: 22,
  },
  agentTaskCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 15,
    paddingHorizontal: 14,
    paddingVertical: 14,
    minHeight: 82,
    shadowColor: '#37423D',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 4,
  },
  agentTaskIcon: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
  },
  agentTaskText: {
    flex: 1,
    marginHorizontal: 12,
  },
  agentTaskTitle: {
    fontFamily: 'Harmattan-SemiBold',
    fontSize: 17,
    color: '#37423D',
  },
  agentTaskDescription: {
    fontFamily: 'Raleway-Regular',
    fontSize: 11,
    lineHeight: 16,
    color: '#6B716D',
    marginTop: -2,
  },
  agentTaskCheck: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 1.5,
    borderColor: '#899878',
    alignItems: 'center',
    justifyContent: 'center',
  },
  agentTaskCheckCompleted: {
    backgroundColor: '#899878',
  },
  agentGuidedTaskCard: {
    minHeight: 104,
    borderWidth: 1,
    borderColor: '#E8E6D7',
  },
  agentGuidedTaskMeta: {
    fontFamily: 'Raleway-SemiBold',
    fontSize: 10,
    color: '#607950',
    marginTop: 6,
  },
  agentGuidedStartButton: {
    minWidth: 66,
    minHeight: 38,
    borderRadius: 19,
    paddingHorizontal: 11,
    backgroundColor: '#DDE7C7',
    borderWidth: 1,
    borderColor: '#37423D',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 3,
  },
  agentGuidedStartText: {
    fontFamily: 'Raleway-SemiBold',
    fontSize: 12,
    color: '#37423D',
  },
  guidedSessionScreen: {
    flex: 1,
    backgroundColor: '#FCF9ED',
    paddingTop: 54,
    paddingHorizontal: 22,
    paddingBottom: 110,
  },
  guidedSessionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  guidedSessionBackButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
  },
  guidedSessionDuration: {
    fontFamily: 'Raleway-SemiBold',
    fontSize: 11,
    letterSpacing: 1.1,
    color: '#918E8E',
  },
  guidedSessionHeaderSpacer: {
    width: 42,
    height: 42,
  },
  guidedSessionContent: {
    flex: 1,
    alignItems: 'center',
    paddingTop: 18,
  },
  guidedSessionTitle: {
    fontFamily: 'Caveat-Regular',
    fontSize: 37,
    lineHeight: 44,
    color: '#37423D',
    textAlign: 'center',
  },
  guidedSessionDescription: {
    maxWidth: 315,
    fontFamily: 'Raleway-Regular',
    fontSize: 13,
    lineHeight: 20,
    color: '#6B716D',
    textAlign: 'center',
    marginTop: 8,
  },
  guidedActivityOrb: {
    width: 174,
    height: 174,
    borderRadius: 87,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 33,
    borderWidth: 1,
    borderColor: '#FFFFFF',
  },
  guidedTimer: {
    fontFamily: 'Raleway-Regular',
    fontSize: 56,
    lineHeight: 64,
    letterSpacing: 1,
    color: '#37423D',
    marginTop: 24,
    fontVariant: ['tabular-nums'],
  },
  guidedPhaseBlock: {
    alignItems: 'center',
    minHeight: 70,
    marginTop: 4,
  },
  guidedPhaseTitle: {
    fontFamily: 'Caveat-SemiBold',
    fontSize: 26,
    color: '#37423D',
  },
  guidedPhaseText: {
    fontFamily: 'Raleway-Regular',
    fontSize: 12,
    color: '#6B716D',
    marginTop: -4,
  },
  guidedPhaseCount: {
    fontFamily: 'Raleway-SemiBold',
    fontSize: 30,
    lineHeight: 34,
    color: '#6B716D',
    fontVariant: ['tabular-nums'],
  },
  guidedGuidanceBlock: {
    width: '100%',
    maxWidth: 335,
    minHeight: 92,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
    marginTop: 6,
  },
  guidedGuidanceLabel: {
    fontFamily: 'Raleway-SemiBold',
    fontSize: 10,
    lineHeight: 14,
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    color: '#918E8E',
    textAlign: 'center',
    marginBottom: 5,
  },
  guidedGuidanceText: {
    fontFamily: 'Raleway-Regular',
    fontSize: 12,
    lineHeight: 18,
    color: '#6B716D',
    textAlign: 'center',
  },
  guidedAffirmationText: {
    maxWidth: 310,
    fontFamily: 'Caveat-SemiBold',
    fontSize: 27,
    lineHeight: 32,
    color: '#37423D',
  },
  guidedPausedText: {
    fontFamily: 'Raleway-Regular',
    fontSize: 10,
    lineHeight: 14,
    color: '#918E8E',
    textAlign: 'center',
    marginTop: 2,
  },
  guidedActivePrompt: {
    minHeight: 46,
    fontFamily: 'Raleway-Regular',
    fontSize: 12,
    lineHeight: 18,
    color: '#6B716D',
    textAlign: 'center',
    marginTop: 7,
  },
  guidedSafetyNote: {
    fontFamily: 'Raleway-Regular',
    fontSize: 11,
    lineHeight: 17,
    textAlign: 'center',
    color: '#756B9B',
    paddingHorizontal: 16,
    marginTop: 19,
  },
  guidedAudioControls: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 9,
    marginTop: 'auto',
  },
  guidedAudioControl: {
    minHeight: 42,
    borderRadius: 21,
    paddingHorizontal: 13,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E8E6D7',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  guidedAudioControlMuted: {
    backgroundColor: '#F3F1E8',
  },
  guidedAudioControlText: {
    fontFamily: 'Raleway-SemiBold',
    fontSize: 11,
    color: '#37423D',
  },
  guidedAudioNotice: {
    fontFamily: 'Raleway-Regular',
    fontSize: 10,
    lineHeight: 15,
    color: '#918E8E',
    textAlign: 'center',
    marginTop: 9,
    minHeight: 15,
  },
  guidedPrimaryButton: {
    minWidth: 188,
    minHeight: 52,
    borderRadius: 26,
    backgroundColor: '#DDE7C7',
    borderWidth: 1.5,
    borderColor: '#37423D',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 9,
    marginTop: 22,
  },
  guidedPrimaryButtonText: {
    fontFamily: 'Raleway-SemiBold',
    fontSize: 15,
    color: '#37423D',
  },
  guidedPauseButton: {
    minWidth: 142,
    minHeight: 50,
    borderRadius: 25,
    backgroundColor: '#D5B9B2',
    borderWidth: 1,
    borderColor: '#37423D',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginTop: 22,
  },
  guidedPauseButtonText: {
    fontFamily: 'Raleway-SemiBold',
    fontSize: 15,
    color: '#37423D',
  },
  guidedCompletionContent: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingBottom: 40,
  },
  guidedCompletionTitle: {
    maxWidth: 290,
    fontFamily: 'Caveat-Regular',
    fontSize: 38,
    lineHeight: 44,
    color: '#37423D',
    textAlign: 'center',
    marginTop: 26,
  },
  guidedCompletionText: {
    maxWidth: 295,
    fontFamily: 'Raleway-Regular',
    fontSize: 13,
    lineHeight: 20,
    color: '#6B716D',
    textAlign: 'center',
    marginTop: 11,
  },
  guidedExitOverlay: {
    flex: 1,
    backgroundColor: 'rgba(55, 66, 61, 0.42)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 30,
  },
  guidedExitCard: {
    width: '100%',
    maxWidth: 340,
    backgroundColor: '#FCF9ED',
    borderRadius: 22,
    padding: 23,
    shadowColor: '#37423D',
    shadowOffset: { width: 0, height: 7 },
    shadowOpacity: 0.22,
    shadowRadius: 12,
    elevation: 8,
  },
  guidedExitTitle: {
    fontFamily: 'Caveat-Regular',
    fontSize: 32,
    color: '#37423D',
    textAlign: 'center',
  },
  guidedExitText: {
    fontFamily: 'Raleway-Regular',
    fontSize: 13,
    lineHeight: 19,
    color: '#6B716D',
    textAlign: 'center',
    marginTop: 6,
  },
  guidedExitActions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 22,
  },
  guidedStayButton: {
    flex: 1,
    minHeight: 46,
    borderRadius: 23,
    backgroundColor: '#DDE7C7',
    borderWidth: 1,
    borderColor: '#37423D',
    alignItems: 'center',
    justifyContent: 'center',
  },
  guidedStayButtonText: {
    fontFamily: 'Raleway-SemiBold',
    fontSize: 14,
    color: '#37423D',
  },
  guidedLeaveButton: {
    flex: 1,
    minHeight: 46,
    borderRadius: 23,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#918E8E',
    alignItems: 'center',
    justifyContent: 'center',
  },
  guidedLeaveButtonText: {
    fontFamily: 'Raleway-SemiBold',
    fontSize: 14,
    color: '#6B716D',
  },
  // -------- MY PLANT PAGE --------
  myPlantBackground: {
    flex: 1,
  },
  myPlantSafeArea: {
    flex: 1,
  },
  myPlantHeader: {
    alignItems: 'center',
    paddingTop: 12,
    paddingHorizontal: 22,
    zIndex: 2,
  },
  myPlantTitle: {
    fontFamily: 'Caveat-Bold',
    fontSize: 42,
    lineHeight: 48,
    textAlign: 'center',
    textShadowColor: 'rgba(252, 249, 237, 0.72)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 5,
  },
  myPlantSubtitle: {
    fontFamily: 'Raleway-SemiBold',
    fontSize: 13,
    lineHeight: 19,
    textAlign: 'center',
    textShadowColor: 'rgba(252, 249, 237, 0.82)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
  },
  myPlantGardenerBubble: {
    width: '100%',
    maxWidth: 350,
  },
  myPlantGardenerPanel: {
    width: '100%',
    maxWidth: 350,
    marginTop: 12,
    position: 'relative',
  },
  myPlantGardenerCloseButton: {
    position: 'absolute',
    top: 10,
    right: 10,
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 15,
    backgroundColor: 'rgba(252, 249, 237, 0.82)',
  },
  myPlantGardenerIconButton: {
    width: 56,
    height: 56,
    marginTop: 14,
    borderRadius: 28,
    padding: 3,
    backgroundColor: 'rgba(252, 249, 237, 0.9)',
    borderWidth: 1,
    borderColor: '#E8E6D7',
    shadowColor: '#37423D',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.18,
    shadowRadius: 4,
    elevation: 3,
  },
  myPlantGardenerIcon: {
    width: '100%',
    height: '100%',
    borderRadius: 25,
  },
  myPlantStage: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-end',
    paddingBottom: 112,
  },
  myPlantVisual: {
    width: '100%',
    maxWidth: 390,
    height: 430,
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  myPlantImage: {
    width: 340,
    height: 380,
  },
  myPlantImageStageFour: {
    width: 270,
    height: 410,
  },
  myPlantCenteredState: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 28,
    paddingBottom: 105,
  },
  myPlantErrorCard: {
    width: '100%',
    maxWidth: 330,
    alignItems: 'center',
    padding: 22,
    borderRadius: 20,
    backgroundColor: 'rgba(252, 249, 237, 0.94)',
    borderWidth: 1,
    borderColor: '#E8E6D7',
  },
  myPlantErrorTitle: {
    fontFamily: 'Caveat-Regular',
    fontSize: 29,
    color: '#37423D',
    textAlign: 'center',
  },
  myPlantErrorText: {
    fontFamily: 'Raleway-Regular',
    fontSize: 12,
    lineHeight: 18,
    color: '#6B716D',
    textAlign: 'center',
    marginTop: 6,
  },
  // ---------------------------------
})
